@startuml archi
class "Radiation Summary Report" as RSR <<Composition>> #ffe6cc ##b86611
class "Radiation Dose Summary" as DoseSummary <<Observation>> #d5e8d4 ##green 
class "Pregnancy Status (IPS)" as PregnancyStatus <<Observation>> #fff2cc ##b3880c
class "Indication Observation" as Indication <<Observation>> #fff2cc ##b3880c
class "Modality Device" as Modality <<Device>> #34b1eb ##217aa3
class "ImagingStudy" as ImagingStudy #a3e7ff ##34b1eb
class "Patient" as Patient #a3e7ff ##34b1eb
class "Practitioner" as Practitioner #a3e7ff ##34b1eb

DoseSummary   -down-> Patient : subject[1..1]
DoseSummary   -down-> Practitioner : performer[1..1]
DoseSummary   -down-> ImagingStudy : partOf[0..1]
DoseSummary   -down-> Modality : device[0..1]
PregnancyStatus  -down-> Patient : subject[1..1]
Indication  -down-> Patient : subject[1..1]
RSR -down-> Patient : subject[1..1]
RSR  -down-> DoseSummary  : section.entry[1..1]
RSR  -down-> PregnancyStatus : section.entry[0..1]
RSR  -down-> Indication : section.entry[0..1]
@enduml