@startuml
skinparam monochrome true

object  CTRadiationDoseSummary #white { 
  id = 139
  study-instance-uid = 1.2.840.121.3.32.0.1.1323423 
}

object  Patient #white {
  id = 56
  identifier = PAT3421|pidauth1
  name = Pascal Dupont
}

object  ImagingStudy #white { 
  id = 342
  study-instance-uid = 1.2.840.121.3.32.0.1.1323423
}

object  Practitioner #white { 
  id = 33
  identifier = pract67 | practauth1
  name = John Moore
}

object  ModalityDevice #white { 
  id = 539
  device-serial-number = 5445A343
  application-entity = CT01
}

CTRadiationDoseSummary -d-> Patient : "subject"
CTRadiationDoseSummary -d-> ImagingStudy : "partOf"
CTRadiationDoseSummary -d-> Practitioner : "performer"
CTRadiationDoseSummary -d-> ModalityDevice : "device"
ImagingStudy -> Patient : "subject"
@enduml