@startuml usecase1
hide footbox

actor Radiologist
participant "Acquisition Modality" as Modality
participant "Dose Management System\n(DMS)" as DMS
participant "Radiology Information System \n(RIS)" as RIS
participant "Electronic Health Record \n(EHR)" as EHR

group IHE REM Profile
  activate Modality
  Modality -> Modality : Perform study
  Modality -> DMS : RAD-62 Store Dose\nInformation (RDSR)
  activate DMS 
  deactivate Modality
end

DMS -> DMS : Compose FHIR Dose Summary
activate RIS
RIS -> DMS : GET FHIR Dose Summary 
DMS --> RIS:
deactivate DMS

Radiologist -> RIS: Dictate report
RIS -> RIS : Consolidate dictation\nand dose summary
Radiologist -> RIS: Sign report
RIS -> EHR : Share imaging report
activate EHR
deactivate RIS

@enduml