# ╭─────────────────────────────────ImplementationGuide-fish.json──────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see:                                                                    │
# │  https://fshschool.org/docs/sushi/configuration/#full-configuration                            │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: hl7.fhir.uv.fhir-radiation-dose-summary-ig
canonical: http://hl7.org/fhir/fhir-radiation-dose-summary-ig
version: 0.1.0
name: RadiationDoseSummaryForDiagnosticProceduresOnFHIR
title: Radiation Dose Summary for Diagnostic Procedures on FHIR
status: draft
publisher: 
  - name: HL7 Imaging Integration Working Group
  - url: http://www.hl7.org/Special/committees/imagemgt/index.cfm
contact:
  - name: HL7 Imaging Integration Workgroup
    telecom:
      - system: url
        value: http://www.hl7.org/Special/committees/imagemgt/index.cfm
  - name: Abderrazek Boufahja
    telecom:
      - system: email
        value: abderrazek.boufahja@ge.com
description: This IG standardizes the sharing of minimal radiation information following a performed exam. 
  Minimal radiation information is required by multiple stakeholders including RIS, EHR, and national/regional stakeholders and 
  their associated regulations. This IG standardizes data sharing from dose management systems to third parties. 
  The IG exposes radiation information related to (and coming from) imaging procedures, but not medications.
jurisdiction: "http://unstats.un.org/unsd/methods/m49/m49.htm#001"
license: CC0-1.0
fhirVersion: 4.0.1
parameters:
  show-inherited-invariants: false
  generate-turtle: false
  usage-stats-opt-out: true
copyrightYear: 2020+
releaseLabel: ci-build

pages:
  index.md:
    title: Home
    generation: markdown
  background.md:
    title: Background
    generation: markdown
  archi.md:
    title: Architecture and Implementation
    generation: markdown
  testing.md:
    title: Testing and Conformance
    generation: markdown


# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  IG Home: index.html
  Contents: toc.html
  Background: background.html
  Architecture &amp; Implementation: archi.html
  Testing &amp; Conformance: testing.html
  Artifact Index: artifacts.html